BENCH Fix all remaining layers to new decoding scheme.
----------------------------------------------------------
BENCHMARK_MARKER_DO_NOT_CHANGE
----------------------------------------------------------

TEST BENCHMARKS
?   	github.com/gconnell/gopacket	[no test files]
If you see a crash here, it's serious business.  Report it!
Send this number with any crash reports: 1356111769970496000
No crash to see here... continuing with testing
PASS
BenchmarkTypeAssertion	500000000	         7.97 ns/op
BenchmarkMapLookup	50000000	        37.0 ns/op
BenchmarkNilMapLookup	100000000	        25.2 ns/op
BenchmarkNilMapLookupWithNilCheck	2000000000	         0.80 ns/op
BenchmarkArrayLookup	2000000000	         0.80 ns/op
BenchmarkLayerClassSliceContains	2000000000	         1.33 ns/op
BenchmarkLayerClassMapContains	50000000	        46.1 ns/op
BenchmarkLazyNoCopyEthLayer	 5000000	       746 ns/op
BenchmarkLazyNoCopyIPLayer	 1000000	      1204 ns/op
BenchmarkLazyNoCopyTCPLayer	 1000000	      1864 ns/op
BenchmarkLazyNoCopyAllLayers	 1000000	      2122 ns/op
BenchmarkDefault	 1000000	      2086 ns/op
BenchmarkLazy	 5000000	       727 ns/op
BenchmarkNoCopy	 1000000	      1690 ns/op
BenchmarkLazyNoCopy	 5000000	       351 ns/op
BenchmarkAlloc	10000000	       141 ns/op
BenchmarkFlow	10000000	       238 ns/op
BenchmarkEndpoints	100000000	        27.8 ns/op
BenchmarkTCPLayerFromDecodedPacket	100000000	        14.4 ns/op
BenchmarkTCPLayerClassFromDecodedPacket	20000000	        77.6 ns/op
BenchmarkCheckEthernetPrefix	50000000	        38.3 ns/op
BenchmarkDecodePacketIPSecESP	 1000000	      1199 ns/op
ok  	github.com/gconnell/gopacket/layers	51.115s
?   	github.com/gconnell/gopacket/pcap	[no test files]
?   	github.com/gconnell/gopacket/pfring	[no test files]

PCAP BENCHMARK
Reading file once through to hopefully cache most of it
Read in file /tmp/gopacket_benchmark.pcap , total of 341401548 bytes
1/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 857.765ms, 693ns per packet
Read in 1237119 packets in 2.253597s, 1.821us per packet
Time to both read and process: 3.111405s
2/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 893.273ms, 722ns per packet
Read in 1237119 packets in 2.811718s, 2.272us per packet
Time to both read and process: 3.705046s
3/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 709.867ms, 573ns per packet
Read in 1237119 packets in 2.329755s, 1.883us per packet
Time to both read and process: 3.039661s
4/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 692.044ms, 559ns per packet
Read in 1237119 packets in 2.632425s, 2.127us per packet
Time to both read and process: 3.32451s
5/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 689.795ms, 557ns per packet
Read in 1237119 packets in 2.367993s, 1.914us per packet
Time to both read and process: 3.057826s
6/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 701.801ms, 567ns per packet
Read in 1237119 packets in 2.827481s, 2.285us per packet
Time to both read and process: 3.529322s
7/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 692.379ms, 559ns per packet
Read in 1237119 packets in 2.354448s, 1.903us per packet
Time to both read and process: 3.046867s
8/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 690.963ms, 558ns per packet
Read in 1237119 packets in 2.360221s, 1.907us per packet
Time to both read and process: 3.051224s
9/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 684.409ms, 553ns per packet
Read in 1237119 packets in 2.355436s, 1.903us per packet
Time to both read and process: 3.039882s
10/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 700.776ms, 566ns per packet
Read in 1237119 packets in 2.847259s, 2.301us per packet
Time to both read and process: 3.548075s
----------------------------------------------------------
BENCHMARKING AGAINST COMMIT b4d50fb081bd168975550d9fbbac557a2f7de8af
----------------------------------------------------------

OLD TEST BENCHMARKS
?   	github.com/gconnell/gopacket	[no test files]
# github.com/gconnell/gopacket/layers
layers/arp.go:38: undefined: gopacket.DecodeResult
layers/cdp.go:36: undefined: gopacket.DecodeResult
layers/ctp.go:67: undefined: gopacket.DecodeResult
layers/ctp.go:83: undefined: gopacket.DecodeResult
layers/dot1q.go:28: undefined: gopacket.DecodeResult
layers/etherip.go:20: undefined: gopacket.DecodeResult
layers/gre.go:32: undefined: gopacket.DecodeResult
layers/icmp.go:25: undefined: gopacket.DecodeResult
layers/ip6.go:33: undefined: gopacket.DecodeResult
layers/ip6.go:95: undefined: gopacket.DecodeResult
layers/ip6.go:95: too many errors
FAIL	github.com/gconnell/gopacket/layers [build failed]
?   	github.com/gconnell/gopacket/pcap	[no test files]
?   	github.com/gconnell/gopacket/pfring	[no test files]

OLD PCAP BENCHMARK
# github.com/gconnell/gopacket/layers
layers/arp.go:38: undefined: gopacket.DecodeResult
layers/cdp.go:36: undefined: gopacket.DecodeResult
layers/ctp.go:67: undefined: gopacket.DecodeResult
layers/ctp.go:83: undefined: gopacket.DecodeResult
layers/dot1q.go:28: undefined: gopacket.DecodeResult
layers/etherip.go:20: undefined: gopacket.DecodeResult
layers/gre.go:32: undefined: gopacket.DecodeResult
layers/icmp.go:25: undefined: gopacket.DecodeResult
layers/ip6.go:33: undefined: gopacket.DecodeResult
layers/ip6.go:95: undefined: gopacket.DecodeResult
layers/ip6.go:95: too many errors